---
format:
  html:
    mainfont: Tinos
    title-block-banner: false
    toc: false
    number-sections: false
---

# Introducción

Germinación se considera cuando una semilla ha germinado cuando de esta sale la radica (Rodríguez-Quilón et al., 2008). La germinación inicia con la inhibición de agua y activa su metabolismo hasta que la radícula aparezca garantizando que el proceso ha sido exitoso (Rosabal et al., 2014). Para que una semilla germine se necesita de factores internos (la viabilidad del embrión cantidad, calidad de los tejidos de reserva, etc.) y factores externos (la disponibilidad de agua, temperatura, luz, etc.). Por otra parte, según la necesidad de luz estas se dividen en tres grupos: (i) fotoblásticas positivas – son las que requieren luz para germinar –, (ii) fotoblásticas negativas – estas son las que necesitan estar en oscuridad para germinar – y (iii) semillas insensibles – estas no los afecta ni la luz ni la oscuridad (Suárez & Melgarejo, 2010).
La lechuga es una verdura muy importante, cultivándose a nivel mundial. Sin embargo, es muy sensible a los factores ambientales. Principalmente la temperatura siendo 20°C la temperatura óptima y si pasa los 30°C las semillas retrasan su germinación o no germinan (Lemos Neto et al., 2018). Por lo que es necesario germinar en semilleros dando las condiciones aptas para luego trasplantar asegurando un mayor establecimiento del cultivo.

# Objetivos

-   Evaluar el efecto que tiene la luz sobre la germinación de semillas de lechuga,

-   Estimar el tiempo de germinación de semillas tanto con luz y sin luz.
