---
title: "Portada"
format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    number-sections: true
---

#GENERALIDADES SOBRE LAS SEMILLAS: SU PRODUCCIÓN, CONSERVACIÓN Y ALMACENAMIENTO

##ABSTRACT Seeds are plant sexual reproduction unit aimed to multiply and perpetuate the species to which they belong; thus, they are one of the most effective elements to be dispersed both in time and space. Seeds constitute the perennial mechanism that let plants endure from one generation to another. They are also plant moving unit. Seeds are the means by which, even in a passive way, plants find new sites and microenvironments. Every crop must take into account seed quality for its success. Seeds are the starting point for production and it is essential to have a good response under sowing conditions to release vigorous seedlings for achieving top yield. From a sustainable viewpoint, it is impossible to get a good harvest if it does not come from a quality seed, since any crop may have a lower quality than the seed sown, but it is never better than it. Undoubtedly, a good quality seed represents the quintessential strategic input that allows supporting agricultural activities, so enabling significantly to improve its production in terms of quality and profitability. Therefore, the works aimed at stimulating and extending germination and subsequent seed preservation are of great scientific and technical interest, to raise sustainable crop productivity and face environmental changes more appropriately.
