---
title: "referencias"
format: html
editor: visual
---

Bashri, G., Patel, A., Singh, R., Parihar, P., & Prasad, S. M. (2017). Mineral Solubilization by Microorganism: Mitigating Strategy in Mineral Deficient Soil. In: Patra, J., Vishnuprasad, C. and Das, G. (eds) Microbial Biotechnology. Springer, Singapur. \[ [Links](javascript:void(0);) \]

Castelán, R., López, I. C., Tamariz, J. V., Linares, F. G., & Cruz, M. A. (2017). Erosión y pérdida de nutrientes en diferentes sistemas agrícolas de una microcuenca en la zona periurbana de la ciudad de Puebla, México. Terra Latinoamericana, 35, 229-235. \[ [Links](javascript:void(0);) \]

Cotrina-Cabello, V. R., Alejos-Patiño, I. W., Cotrina-Cabello, G. G., Cordova-Mendoza, P., & Cordova-Barrios, I. C. (2020). Efectos de abonos orgánicos en suelos agrícolas de Purupampa Panao, Perú. Centro Agrícola, 47(2), 31-40. \[ [Links](javascript:void(0);) \]

Cristo, E., González, M., & Pérez, N. (2016). Evaluación de nuevos cultivares de arroz (Oryza sativa L.) en condiciones de bajos suministros de agua y fertilizante en la provincia de Pinar del Río. Cult. Trop., 37(2), 127-133. \[ [Links](javascript:void(0);) \]

Espinosa, K., & Molina, M. (2015). Evaluación agronómica de hortalizas de hoja, col china (Brassica campestris) y perejil (Petroselinum crispum) con fertilizantes orgánicos. UTCiencia, 2(1), 29-34 \[ [Links](javascript:void(0);) \]
